/** new_tool.js */
/**
 * 1. Imports
 * 2. Public functions
 *    -  Tool
 * 3. Loacal functions
 */
/** Imports */
import CardContainerPlus from './moduls/CardContainerPlus.js';
import FormElements from './moduls/FormElements.js';
import { addListenerByAttr } from './common.js';

/** Public functions */
var newTool = {
    loadNewTool: function () {
        // Load framework
        let framework = '<div id="new_tool" class="display-flex flex-column full-screen"><div id="back_to_tool_header" class="modul-title display-flex"><div id="back_to_tool"><i class="fas fa-arrow-left align-middle"></i></div><div class="modul-title-text"><span id="back_to_tool_text" class="unselectable align-middle">Eszközök</span></div></div><div class="display-flex flex-fill"><div class="flex-fill col-1"></div><div class="flex-fill col-10"><div class="row page-content"> <div class="col-md-6 col-12 right-border-form"> <h2 class="task-subtitle">Adatok</h2> <div id="new_tool_data"></div> <div class="newtask-buttoncontainer d-flex justify-content-start"> <button type="submit" class="btn btn-primary addnewtask-button">Létrehoz</button> <button type="reset" class="btn btn-primary addnewtask-button grey-button">Mégse</button> </div></div><div class="col-md-6 col-12"><h2 class="task-subtitle">Kép hozzáadása</h2><div id="task_pic_shell" class="img_input_shell"><input type="file" id="new_task_pic" class="img-input"><img id="new_t_pic_prev" class="img_inp_preview"><i class="fas fa-cloud-upload-alt img_input_icon"></i></div></div></div></div></div><div class="flex-fill col-1"> </div></div></div>';
        document.getElementById("resources_content").innerHTML = framework;

        // Load data entry form
        let shellId = "new_tool_data";
        let formData = Local.getFromData();
        CardContainerPlus.Create(formData, shellId, Local.getFromHTML);
        addListenerByAttr("new_" + shellId, "click", Local.openCollapse);

        FormElements.B.Image('task_pic_shell', 'new_task_pic', 'new_t_pic_prev');


    }
};
export default newTool;

let Local = {
    getFromData: function () {
        return newPartnerData;
    },
    getFromHTML: function (objectItem, shellId) {
        switch (objectItem.Type) {
            case "Write":
                FormElements.B.Write(objectItem.Id, objectItem.Name, shellId);
                break;
            case "Select":
                FormElements.B.Select(objectItem.Id, objectItem.Name, shellId, objectItem.Opportunities);
                break;
            case "SelectOrNew":
                FormElements.B.SelectOrNew(objectItem.Id, objectItem.Name, shellId, objectItem.Opportunities);
                break;
            case "DateTime":
                FormElements.B.DateTime(objectItem.Id, objectItem.Name, shellId);
                break;
            default:
                break;
        }
    },
    openCollapse: function (id) {
        //full card will be generated by getFilterHTML function
        let defaultId = id.split('_')[1];
        let element = document.getElementById('collapse_' + defaultId);
        if (element.style.display === "block") {
            element.style.display = "none";
        } else {
            element.style.display = "block";
        }
    }
};

let newPartnerData = [
    {
        Id: "2234",
        Name: "Eszköz neve:",
        Type: "Write",
        Default: ""
    },
    {
        Id: "2235",
        Name: "Eszköz típusa:",
        Type: "SelectOrNew",
        Default: "Szervíz",
        Opportunities: ["Szervíz", "Szállítás", "Kereskedés"]
    },
    {
        Id: "2236",
        Name: "Használatbavétel kezdete:",
        Type: "DateTime",
        Default: ""
    },
    {
        Id: "2237",
        Name: "Karbantartást igényel (nap):",
        Type: "Write",
        Default: ""
    },
    {
        Id: "2238",
        Name: "Rövid leírás:",
        Type: "Write",
        Default: ""
    }

];
/*
var partner_m_structure = [
    "Name",
    "Megrendelő",
    "Id"
];

var partner_m_structure_2 = [
    "Name",
    "Type",
    "Megrendelő",
    null, //"Létrehozás",
    "Határidő",
    "Cím",
    "Leírás"
];

*/